package cmd

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// go install names the binary after the module ("worktrees"), while the repo
// build scripts produce wt.bin/wt.bin.exe behind wt entry-point wrappers.
// When the running binary detects it carries the full name, it acts purely
// as an installer: `worktrees <dir>` copies itself into dir as wt.bin[.exe]
// and writes the platform's wt entry point there; without a path it prints
// only the usage. On Windows the binary deliberately never exists as
// wt.exe, which would shadow the wt.cmd wrapper in cmd's lookup.

// selfInstallPosixScript is the POSIX `wt` entry point (mirrors shell/wt).
const selfInstallPosixScript = `#!/bin/sh
# wt entry point (generated by the worktrees binary). Exec's the real binary
# (wt.bin next to this script). For cd-on-Enter install the shell function:
#   eval "$(/path/to/wt shell-init zsh)"    # or: wt shell-init zsh --install
self="$0"
if [ -L "$self" ]; then
  self="$(readlink -f "$self" 2>/dev/null || echo "$self")"
fi
exec "$(dirname "$self")/wt.bin" "$@"
`

// selfInstallCmdScript is the cmd.exe `wt.cmd` entry point (mirrors
// shell/wt.cmd); written with CRLF line endings.
const selfInstallCmdScript = `@echo off
rem wt entry point (generated by the worktrees binary): runs the sibling
rem wt.bin.exe and cds this console to the worktree selected with Enter.
rem No setlocal on purpose: the final cd must apply to the calling session.
set "WT_EXE=%~dp0wt.bin.exe"
if not exist "%WT_EXE%" set "WT_EXE=wt.bin.exe"
set "WT_CD_TMP=%TEMP%\wt-cd-%RANDOM%%RANDOM%.tmp"
"%WT_EXE%" --cd-file "%WT_CD_TMP%" %*
set "WT_CD_EXIT=%ERRORLEVEL%"
if not exist "%WT_CD_TMP%" goto wt_cd_done
set "WT_CD_DIR="
set /p WT_CD_DIR=<"%WT_CD_TMP%"
del "%WT_CD_TMP%" >nul 2>&1
if not defined WT_CD_DIR goto wt_cd_done
cd /d "%WT_CD_DIR%"
:wt_cd_done
set "WT_EXE="
set "WT_CD_TMP="
set "WT_CD_DIR="
exit /b %WT_CD_EXIT%
`

// isFullNameInvocation reports whether the binary at exe carries the
// module's full name ("worktrees", the name go install produces) rather than
// one of the wt entry-point names.
func isFullNameInvocation(exe string) bool {
	// Split on both separators: exe comes from os.Executable (native), but
	// staying separator-agnostic costs nothing and keeps tests portable.
	base := filepath.Base(strings.ReplaceAll(exe, `\`, `/`))
	if strings.EqualFold(filepath.Ext(base), ".exe") {
		base = base[:len(base)-len(".exe")]
	}
	return strings.EqualFold(base, "worktrees")
}

// writeFileAtomic writes content via a temp file + rename so a concurrent
// reader never sees a half-written entry point.
func writeFileAtomic(path string, content []byte, mode os.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".wt-install-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		os.Remove(name)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(name)
		return err
	}
	if err := os.Chmod(name, mode); err != nil {
		os.Remove(name)
		return err
	}
	if err := os.Rename(name, path); err != nil {
		os.Remove(name)
		return err
	}
	return nil
}

// selfInstallTo materializes the wt entry points in dir (created if
// missing): a copy of the binary at exe as wt.bin[.exe] plus the platform's
// wt entry-point script. The path was given explicitly, so existing files
// are always overwritten.
func selfInstallTo(exe, dir, goos string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create %s: %w", dir, err)
	}

	binName := "wt.bin"
	if goos == "windows" {
		binName += ".exe"
	}
	data, err := os.ReadFile(exe)
	if err != nil {
		return fmt.Errorf("read own binary: %w", err)
	}
	if err := writeFileAtomic(filepath.Join(dir, binName), data, 0o755); err != nil {
		return fmt.Errorf("install %s: %w", binName, err)
	}

	if goos == "windows" {
		body := strings.ReplaceAll(selfInstallCmdScript, "\n", "\r\n")
		if err := writeFileAtomic(filepath.Join(dir, "wt.cmd"), []byte(body), 0o755); err != nil {
			return fmt.Errorf("install wt.cmd: %w", err)
		}
	} else {
		if err := writeFileAtomic(filepath.Join(dir, "wt"), []byte(selfInstallPosixScript), 0o755); err != nil {
			return fmt.Errorf("install wt: %w", err)
		}
	}
	return nil
}

// bootstrapUsageFor is what the full-name binary prints when no install
// path is given: worktrees requires the target directory as its one
// parameter. The full CLI help deliberately stays behind the wt name —
// running `worktrees` is a bootstrap step, not a way to drive the tool.
func bootstrapUsageFor(goos string) string {
	if goos == "windows" {
		return `worktrees requires the path to install the wt entry points into:

  worktrees C:\tools\wt

That copies into the given directory (created if missing):

  wt.bin.exe   the real binary
  wt.cmd       entry point — type wt (it also cds into the worktree you pick with Enter)

No wt.exe is ever created: it would shadow wt.cmd in cmd's lookup.
Afterwards add that directory to your PATH and run wt inside any git repo.
`
	}
	return `worktrees requires the path to install the wt entry points into:

  worktrees ~/.local/bin

That copies into the given directory (created if missing):

  wt.bin   the real binary
  wt       entry point — run this

Afterwards put that directory on your PATH, then install the shell
integration for cd-on-Enter:

  wt shell-init zsh --install   (or: bash; then restart your shell)
`
}

// installDoneFor is printed after a successful install into dir: how to
// finish setting up on the given platform.
func installDoneFor(dir, goos string) string {
	if goos == "windows" {
		return fmt.Sprintf(`wt entry points installed in %s:

  wt.bin.exe   the real binary
  wt.cmd       entry point — type wt (it also cds into the worktree you pick with Enter)

To finish setting up:

  1. Add %s to your PATH.
  2. Run wt inside any git repo.

For the full command reference run: wt --help
`, dir, dir)
	}
	wtPath := filepath.Join(dir, "wt")
	return fmt.Sprintf(`wt entry points installed in %s:

  wt.bin   the real binary
  wt       entry point — run this

To finish setting up:

  1. Put %s on your PATH (or call %s directly).
  2. Install the shell integration for cd-on-Enter:
       %s shell-init zsh --install   (or: bash; then restart your shell)
  3. Run wt inside any git repo.

For the full command reference run: wt --help
`, dir, dir, wtPath, wtPath)
}

// runBootstrap is the whole program when invoked under the full name
// ("worktrees"): with exactly one path argument it installs the wt entry
// points there; anything else prints the usage — never the wt CLI.
func runBootstrap(exe string, args []string, goos string, out, errOut io.Writer) int {
	if len(args) != 1 || strings.HasPrefix(args[0], "-") {
		fmt.Fprint(errOut, bootstrapUsageFor(goos))
		return 2
	}
	dir := args[0]
	if err := selfInstallTo(exe, dir, goos); err != nil {
		fmt.Fprintf(errOut, "worktrees: install: %v\n", err)
		return 1
	}
	fmt.Fprint(out, installDoneFor(dir, goos))
	return 0
}
