package cmd

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// go install names the binary after the module ("worktrees"), while the repo
// build scripts produce wt.bin/wt.bin.exe behind wt entry-point wrappers.
// When the running binary detects it carries the full name, it bootstraps
// that same layout next to itself: it copies itself as wt.bin[.exe] and
// writes the platform's wt entry point. `go install .` (or @latest) followed
// by any `worktrees` invocation therefore yields a working `wt` — and on
// Windows the binary deliberately never exists as wt.exe, which would shadow
// the wt.cmd wrapper in cmd's lookup.

// selfInstallPosixScript is the POSIX `wt` entry point (mirrors shell/wt).
const selfInstallPosixScript = `#!/bin/sh
# wt entry point (generated by the worktrees binary). Exec's the real binary
# (wt.bin next to this script). For cd-on-Enter install the shell function:
#   eval "$(/path/to/wt shell-init zsh)"    # or: wt shell-init zsh --install
self="$0"
if [ -L "$self" ]; then
  self="$(readlink -f "$self" 2>/dev/null || echo "$self")"
fi
exec "$(dirname "$self")/wt.bin" "$@"
`

// selfInstallCmdScript is the cmd.exe `wt.cmd` entry point (mirrors
// shell/wt.cmd); written with CRLF line endings.
const selfInstallCmdScript = `@echo off
rem wt entry point (generated by the worktrees binary): runs the sibling
rem wt.bin.exe and cds this console to the worktree selected with Enter.
rem No setlocal on purpose: the final cd must apply to the calling session.
set "WT_EXE=%~dp0wt.bin.exe"
if not exist "%WT_EXE%" set "WT_EXE=wt.bin.exe"
set "WT_CD_TMP=%TEMP%\wt-cd-%RANDOM%%RANDOM%.tmp"
"%WT_EXE%" --cd-file "%WT_CD_TMP%" %*
set "WT_CD_EXIT=%ERRORLEVEL%"
if not exist "%WT_CD_TMP%" goto wt_cd_done
set "WT_CD_DIR="
set /p WT_CD_DIR=<"%WT_CD_TMP%"
del "%WT_CD_TMP%" >nul 2>&1
if not defined WT_CD_DIR goto wt_cd_done
cd /d "%WT_CD_DIR%"
:wt_cd_done
set "WT_EXE="
set "WT_CD_TMP="
set "WT_CD_DIR="
exit /b %WT_CD_EXIT%
`

// isFullNameInvocation reports whether the binary at exe carries the
// module's full name ("worktrees", the name go install produces) rather than
// one of the wt entry-point names.
func isFullNameInvocation(exe string) bool {
	// Split on both separators: exe comes from os.Executable (native), but
	// staying separator-agnostic costs nothing and keeps tests portable.
	base := filepath.Base(strings.ReplaceAll(exe, `\`, `/`))
	if strings.EqualFold(filepath.Ext(base), ".exe") {
		base = base[:len(base)-len(".exe")]
	}
	return strings.EqualFold(base, "worktrees")
}

// needsRefresh reports whether dst is missing or older than src.
func needsRefresh(src, dst string) bool {
	si, err := os.Stat(src)
	if err != nil {
		return false
	}
	di, err := os.Stat(dst)
	if err != nil {
		return true
	}
	return si.ModTime().After(di.ModTime())
}

// writeFileAtomic writes content via a temp file + rename so a concurrent
// reader never sees a half-written entry point.
func writeFileAtomic(path string, content []byte, mode os.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".wt-install-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		os.Remove(name)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(name)
		return err
	}
	if err := os.Chmod(name, mode); err != nil {
		os.Remove(name)
		return err
	}
	if err := os.Rename(name, path); err != nil {
		os.Remove(name)
		return err
	}
	return nil
}

// selfInstallAt materializes the wt entry points next to the binary at exe:
// a copy of the binary as wt.bin[.exe] plus the platform's wt entry-point
// script. Existing files are refreshed only when the binary is newer (a
// fresh go install). It reports whether anything was written.
func selfInstallAt(exe, goos string) (bool, error) {
	dir := filepath.Dir(exe)
	changed := false

	binName := "wt.bin"
	if goos == "windows" {
		binName += ".exe"
	}
	binPath := filepath.Join(dir, binName)
	if needsRefresh(exe, binPath) {
		data, err := os.ReadFile(exe)
		if err != nil {
			return changed, fmt.Errorf("read own binary: %w", err)
		}
		if err := writeFileAtomic(binPath, data, 0o755); err != nil {
			return changed, fmt.Errorf("install %s: %w", binName, err)
		}
		changed = true
	}

	if goos == "windows" {
		script := filepath.Join(dir, "wt.cmd")
		if needsRefresh(exe, script) {
			body := strings.ReplaceAll(selfInstallCmdScript, "\n", "\r\n")
			if err := writeFileAtomic(script, []byte(body), 0o755); err != nil {
				return changed, fmt.Errorf("install wt.cmd: %w", err)
			}
			changed = true
		}
	} else {
		script := filepath.Join(dir, "wt")
		if needsRefresh(exe, script) {
			if err := writeFileAtomic(script, []byte(selfInstallPosixScript), 0o755); err != nil {
				return changed, fmt.Errorf("install wt: %w", err)
			}
			changed = true
		}
	}
	return changed, nil
}

// exeDirOf returns the directory of exe, splitting on both separators so
// Windows paths parse in unit tests on any host (exe itself comes from
// os.Executable at runtime, so this costs nothing there).
func exeDirOf(exe string) string {
	if i := strings.LastIndexAny(exe, `/\`); i >= 0 {
		return exe[:i]
	}
	return "."
}

// bootstrapHelpFor is everything the full-name binary prints: where the wt
// entry points were materialized and how to finish setting up. The full CLI
// help deliberately stays behind the wt name — running `worktrees` is a
// bootstrap step, not a way to drive the tool.
func bootstrapHelpFor(exe, goos string) string {
	dir := exeDirOf(exe)
	if goos == "windows" {
		return fmt.Sprintf(`wt entry points are installed in %s:

  wt.bin.exe   the real binary
  wt.cmd       entry point — type wt (it also cds into the worktree you pick with Enter)

To finish setting up:

  1. Add %s to your PATH.
  2. Run wt inside any git repo.

For the full command reference run: wt --help
`, dir, dir)
	}
	wtPath := dir + "/wt"
	return fmt.Sprintf(`wt entry points are installed in %s:

  wt.bin   the real binary
  wt       entry point — run this

To finish setting up:

  1. Put %s on your PATH (or call %s directly).
  2. Install the shell integration for cd-on-Enter:
       %s shell-init zsh --install   (or: bash; then restart your shell)
  3. Run wt inside any git repo.

For the full command reference run: wt --help
`, dir, dir, wtPath, wtPath)
}

// runBootstrap is the whole program when invoked under the full name
// ("worktrees"): refresh the wt entry points next to the binary and print
// the bootstrap help — never the wt CLI.
func runBootstrap(exe, goos string, out, errOut io.Writer) int {
	code := 0
	if _, err := selfInstallAt(exe, goos); err != nil {
		fmt.Fprintf(errOut, "worktrees: self-install: %v\n", err)
		code = 1
	}
	fmt.Fprint(out, bootstrapHelpFor(exe, goos))
	return code
}
