package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

// go install names the binary after the module ("worktrees"), while the repo
// build scripts produce wt.bin/wt.bin.exe behind wt entry-point wrappers.
// When the running binary detects it carries the full name, it bootstraps
// that same layout next to itself: it copies itself as wt.bin[.exe] and
// writes the platform's wt entry point. `go install .` (or @latest) followed
// by any `worktrees` invocation therefore yields a working `wt` — and on
// Windows the binary deliberately never exists as wt.exe, which would shadow
// the wt.cmd wrapper in cmd's lookup.

// selfInstallPosixScript is the POSIX `wt` entry point (mirrors shell/wt).
const selfInstallPosixScript = `#!/bin/sh
# wt entry point (generated by the worktrees binary). Exec's the real binary
# (wt.bin next to this script). For cd-on-Enter install the shell function:
#   eval "$(/path/to/wt shell-init zsh)"    # or: wt shell-init zsh --install
self="$0"
if [ -L "$self" ]; then
  self="$(readlink -f "$self" 2>/dev/null || echo "$self")"
fi
exec "$(dirname "$self")/wt.bin" "$@"
`

// selfInstallCmdScript is the cmd.exe `wt.cmd` entry point (mirrors
// shell/wt.cmd); written with CRLF line endings.
const selfInstallCmdScript = `@echo off
rem wt entry point (generated by the worktrees binary): runs the sibling
rem wt.bin.exe and cds this console to the worktree selected with Enter.
rem No setlocal on purpose: the final cd must apply to the calling session.
set "WT_EXE=%~dp0wt.bin.exe"
if not exist "%WT_EXE%" set "WT_EXE=wt.bin.exe"
set "WT_CD_TMP=%TEMP%\wt-cd-%RANDOM%%RANDOM%.tmp"
"%WT_EXE%" --cd-file "%WT_CD_TMP%" %*
set "WT_CD_EXIT=%ERRORLEVEL%"
if not exist "%WT_CD_TMP%" goto wt_cd_done
set "WT_CD_DIR="
set /p WT_CD_DIR=<"%WT_CD_TMP%"
del "%WT_CD_TMP%" >nul 2>&1
if not defined WT_CD_DIR goto wt_cd_done
cd /d "%WT_CD_DIR%"
:wt_cd_done
set "WT_EXE="
set "WT_CD_TMP="
set "WT_CD_DIR="
exit /b %WT_CD_EXIT%
`

// isFullNameInvocation reports whether the binary at exe carries the
// module's full name ("worktrees", the name go install produces) rather than
// one of the wt entry-point names.
func isFullNameInvocation(exe string) bool {
	// Split on both separators: exe comes from os.Executable (native), but
	// staying separator-agnostic costs nothing and keeps tests portable.
	base := filepath.Base(strings.ReplaceAll(exe, `\`, `/`))
	if strings.EqualFold(filepath.Ext(base), ".exe") {
		base = base[:len(base)-len(".exe")]
	}
	return strings.EqualFold(base, "worktrees")
}

// needsRefresh reports whether dst is missing or older than src.
func needsRefresh(src, dst string) bool {
	si, err := os.Stat(src)
	if err != nil {
		return false
	}
	di, err := os.Stat(dst)
	if err != nil {
		return true
	}
	return si.ModTime().After(di.ModTime())
}

// writeFileAtomic writes content via a temp file + rename so a concurrent
// reader never sees a half-written entry point.
func writeFileAtomic(path string, content []byte, mode os.FileMode) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".wt-install-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		os.Remove(name)
		return err
	}
	if err := tmp.Close(); err != nil {
		os.Remove(name)
		return err
	}
	if err := os.Chmod(name, mode); err != nil {
		os.Remove(name)
		return err
	}
	if err := os.Rename(name, path); err != nil {
		os.Remove(name)
		return err
	}
	return nil
}

// selfInstallAt materializes the wt entry points next to the binary at exe:
// a copy of the binary as wt.bin[.exe] plus the platform's wt entry-point
// script. Existing files are refreshed only when the binary is newer (a
// fresh go install). It reports whether anything was written.
func selfInstallAt(exe, goos string) (bool, error) {
	dir := filepath.Dir(exe)
	changed := false

	binName := "wt.bin"
	if goos == "windows" {
		binName += ".exe"
	}
	binPath := filepath.Join(dir, binName)
	if needsRefresh(exe, binPath) {
		data, err := os.ReadFile(exe)
		if err != nil {
			return changed, fmt.Errorf("read own binary: %w", err)
		}
		if err := writeFileAtomic(binPath, data, 0o755); err != nil {
			return changed, fmt.Errorf("install %s: %w", binName, err)
		}
		changed = true
	}

	if goos == "windows" {
		script := filepath.Join(dir, "wt.cmd")
		if needsRefresh(exe, script) {
			body := strings.ReplaceAll(selfInstallCmdScript, "\n", "\r\n")
			if err := writeFileAtomic(script, []byte(body), 0o755); err != nil {
				return changed, fmt.Errorf("install wt.cmd: %w", err)
			}
			changed = true
		}
	} else {
		script := filepath.Join(dir, "wt")
		if needsRefresh(exe, script) {
			if err := writeFileAtomic(script, []byte(selfInstallPosixScript), 0o755); err != nil {
				return changed, fmt.Errorf("install wt: %w", err)
			}
			changed = true
		}
	}
	return changed, nil
}

// maybeSelfInstall bootstraps the wt entry points when the process was
// launched via the full-name binary. Failures are reported but never block
// the actual command.
func maybeSelfInstall() {
	exe, err := os.Executable()
	if err != nil || !isFullNameInvocation(exe) {
		return
	}
	changed, err := selfInstallAt(exe, runtime.GOOS)
	if err != nil {
		fmt.Fprintf(os.Stderr, "wt: self-install: %v\n", err)
		return
	}
	if changed {
		fmt.Fprintf(os.Stderr, "wt: installed wt entry points next to %s\n", exe)
		if runtime.GOOS != "windows" {
			fmt.Fprintf(os.Stderr, "wt: for cd-on-Enter run: %s shell-init zsh --install\n", filepath.Join(filepath.Dir(exe), "wt"))
		}
	}
}
